<script async src="https://cdn.ampproject.org/v0.js"></script> 
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.7.0.js"></script>
<script src="assets/bootstrap-table/tableExport.min.js"></script>
<script src="assets/bootstrap-table/jspdf.min.js"></script>
<script src="assets/bootstrap-table/jspdf.plugin.autotable.js"></script>
<script src="assets/bootstrap-table/bootstrap-table.min.js"></script>
<script src="assets/bootstrap-table/bootstrap-table-export.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script async src="https://cdn.ampproject.org/v0.js"></script> 
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>